Adding config file as a parameter to entrypoint.
osrf/rvizweb pull request #14
Opened 2019-01-15 22:30 UTC by jubeira

See #10; needs https://github.com/osrf/polymer-ros-rviz/pull/15.

To specify a configuration, use `config_file` parameter; e.g:
```
roslaunch rvizweb rvizweb.launch config_file:=/path/to/config/file
```

The configuration file is a JSON just like the one that is displayed in the popup after clicking `LOAD CONFIG` at the left panel.

2019-01-17 19:21 UTC, chapulina requested changes
Works for me with the proposed changes. Mind also adding a section to the README with an example of how to use a custom config file? Thanks!

2019-01-17 19:21 UTC, chapulina commented on config/configuration
> +{
Should we give this file an extension? `.json`?

2019-01-17 19:21 UTC, chapulina commented on launch/rvizweb.launch
> +  <param name="/rvizweb/global_config" type="str" textfile="$(find rvizweb)/config/configuration"/>
```suggestion
  <param name="/rvizweb/global_config" type="str" textfile="$(arg config_file)"/>
```

2019-01-18 18:49 UTC, jubeira commented
Comments addressed; thanks! Added new section to README as well.
@chapulina PTAL.

2019-01-18 19:22 UTC, chapulina approved these changes

2019-01-18 19:22 UTC, merged